/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Registrant = IDL.Record({
  'fullName' : IDL.Text,
  'wantsVegetables' : IDL.Bool,
  'wantsRice' : IDL.Bool,
  'address' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'wantsFruits' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getAllRegistrants' : IDL.Func([], [IDL.Vec(Registrant)], ['query']),
  'getRegistrant' : IDL.Func([IDL.Text], [Registrant], ['query']),
  'getTotalRegistrants' : IDL.Func([], [IDL.Nat], ['query']),
  'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerRegistrant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Registrant = IDL.Record({
    'fullName' : IDL.Text,
    'wantsVegetables' : IDL.Bool,
    'wantsRice' : IDL.Bool,
    'address' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'wantsFruits' : IDL.Bool,
  });
  
  return IDL.Service({
    'getAllRegistrants' : IDL.Func([], [IDL.Vec(Registrant)], ['query']),
    'getRegistrant' : IDL.Func([IDL.Text], [Registrant], ['query']),
    'getTotalRegistrants' : IDL.Func([], [IDL.Nat], ['query']),
    'isRegistered' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerRegistrant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };