/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Student {
    studentId: StudentId;
    name: string;
    course: string;
}
export interface FeedbackSubmission {
    studentId: string;
    timestamp: Time;
    submissionText: string;
    submissionId: SubmissionId;
    assignmentTitle: AssignmentTitle;
}
export type AssignmentTitle = string;
export type Time = bigint;
export interface GeneratedFeedback {
    suggestions: Array<Suggestion>;
    feedbackText: string;
    score: bigint;
    timestamp: Time;
    submissionId: SubmissionId;
}
export interface Suggestion {
    text: string;
}
export type StudentId = string;
export type SubmissionId = bigint;
export interface backendInterface {
    addStudent(studentId: StudentId, name: string, course: string): Promise<void>;
    createSubmission(studentId: StudentId, assignmentTitle: AssignmentTitle, submissionText: string): Promise<SubmissionId>;
    generateFeedback(submissionId: SubmissionId): Promise<GeneratedFeedback>;
    getAllFeedbackForStudent(studentId: StudentId): Promise<Array<GeneratedFeedback>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllSubmissionsByStudent(studentId: StudentId): Promise<Array<FeedbackSubmission>>;
    getFeedback(submissionId: SubmissionId): Promise<GeneratedFeedback>;
    getStudent(studentId: StudentId): Promise<Student>;
    getStudentStats(studentId: StudentId): Promise<{
        totalSubmissions: bigint;
        averageScore: bigint;
    }>;
    getSubmissionById(submissionId: SubmissionId): Promise<FeedbackSubmission>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addStudent(arg0: StudentId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0, arg1, arg2);
            return result;
        }
    }
    async createSubmission(arg0: StudentId, arg1: AssignmentTitle, arg2: string): Promise<SubmissionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubmission(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubmission(arg0, arg1, arg2);
            return result;
        }
    }
    async generateFeedback(arg0: SubmissionId): Promise<GeneratedFeedback> {
        if (this.processError) {
            try {
                const result = await this.actor.generateFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateFeedback(arg0);
            return result;
        }
    }
    async getAllFeedbackForStudent(arg0: StudentId): Promise<Array<GeneratedFeedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedbackForStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedbackForStudent(arg0);
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllSubmissionsByStudent(arg0: StudentId): Promise<Array<FeedbackSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissionsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissionsByStudent(arg0);
            return result;
        }
    }
    async getFeedback(arg0: SubmissionId): Promise<GeneratedFeedback> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedback(arg0);
            return result;
        }
    }
    async getStudent(arg0: StudentId): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return result;
        }
    }
    async getStudentStats(arg0: StudentId): Promise<{
        totalSubmissions: bigint;
        averageScore: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentStats(arg0);
            return result;
        }
    }
    async getSubmissionById(arg0: SubmissionId): Promise<FeedbackSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionById(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
