/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Text;
export const AssignmentTitle = IDL.Text;
export const SubmissionId = IDL.Nat;
export const Suggestion = IDL.Record({ 'text' : IDL.Text });
export const Time = IDL.Int;
export const GeneratedFeedback = IDL.Record({
  'suggestions' : IDL.Vec(Suggestion),
  'feedbackText' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'submissionId' : SubmissionId,
});
export const Student = IDL.Record({
  'studentId' : StudentId,
  'name' : IDL.Text,
  'course' : IDL.Text,
});
export const FeedbackSubmission = IDL.Record({
  'studentId' : IDL.Text,
  'timestamp' : Time,
  'submissionText' : IDL.Text,
  'submissionId' : SubmissionId,
  'assignmentTitle' : AssignmentTitle,
});

export const idlService = IDL.Service({
  'addStudent' : IDL.Func([StudentId, IDL.Text, IDL.Text], [], []),
  'createSubmission' : IDL.Func(
      [StudentId, AssignmentTitle, IDL.Text],
      [SubmissionId],
      [],
    ),
  'generateFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], []),
  'getAllFeedbackForStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(GeneratedFeedback)],
      ['query'],
    ),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubmissionsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeedbackSubmission)],
      ['query'],
    ),
  'getFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], ['query']),
  'getStudent' : IDL.Func([StudentId], [Student], ['query']),
  'getStudentStats' : IDL.Func(
      [StudentId],
      [IDL.Record({ 'totalSubmissions' : IDL.Nat, 'averageScore' : IDL.Int })],
      ['query'],
    ),
  'getSubmissionById' : IDL.Func(
      [SubmissionId],
      [FeedbackSubmission],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Text;
  const AssignmentTitle = IDL.Text;
  const SubmissionId = IDL.Nat;
  const Suggestion = IDL.Record({ 'text' : IDL.Text });
  const Time = IDL.Int;
  const GeneratedFeedback = IDL.Record({
    'suggestions' : IDL.Vec(Suggestion),
    'feedbackText' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'submissionId' : SubmissionId,
  });
  const Student = IDL.Record({
    'studentId' : StudentId,
    'name' : IDL.Text,
    'course' : IDL.Text,
  });
  const FeedbackSubmission = IDL.Record({
    'studentId' : IDL.Text,
    'timestamp' : Time,
    'submissionText' : IDL.Text,
    'submissionId' : SubmissionId,
    'assignmentTitle' : AssignmentTitle,
  });
  
  return IDL.Service({
    'addStudent' : IDL.Func([StudentId, IDL.Text, IDL.Text], [], []),
    'createSubmission' : IDL.Func(
        [StudentId, AssignmentTitle, IDL.Text],
        [SubmissionId],
        [],
      ),
    'generateFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], []),
    'getAllFeedbackForStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(GeneratedFeedback)],
        ['query'],
      ),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubmissionsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeedbackSubmission)],
        ['query'],
      ),
    'getFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], ['query']),
    'getStudent' : IDL.Func([StudentId], [Student], ['query']),
    'getStudentStats' : IDL.Func(
        [StudentId],
        [
          IDL.Record({
            'totalSubmissions' : IDL.Nat,
            'averageScore' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getSubmissionById' : IDL.Func(
        [SubmissionId],
        [FeedbackSubmission],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };