/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StudentId = IDL.Text;
export const SubmissionId = IDL.Nat;
export const AssignmentTitle = IDL.Text;
export const Suggestion = IDL.Record({ 'text' : IDL.Text });
export const Time = IDL.Int;
export const GeneratedFeedback = IDL.Record({
  'suggestions' : IDL.Vec(Suggestion),
  'feedbackText' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'submissionId' : SubmissionId,
});
export const Pin = IDL.Text;
export const InstructorId = IDL.Nat;
export const Instructor = IDL.Record({
  'pin' : Pin,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'instructorId' : InstructorId,
  'department' : IDL.Text,
});
export const Student = IDL.Record({
  'studentId' : StudentId,
  'name' : IDL.Text,
  'course' : IDL.Text,
});
export const FeedbackSubmission = IDL.Record({
  'studentId' : IDL.Text,
  'timestamp' : Time,
  'submissionText' : IDL.Text,
  'submissionId' : SubmissionId,
  'assignmentTitle' : AssignmentTitle,
});
export const SystemStats = IDL.Record({
  'topStudent' : IDL.Opt(
    IDL.Record({ 'studentId' : StudentId, 'averageScore' : IDL.Int })
  ),
  'totalStudents' : IDL.Nat,
  'totalSubmissions' : IDL.Nat,
  'overallAverageScore' : IDL.Int,
});

export const idlService = IDL.Service({
  'addStudent' : IDL.Func([StudentId, IDL.Text, IDL.Text], [], []),
  'addSubmissionNote' : IDL.Func([SubmissionId, IDL.Text], [], []),
  'createSubmission' : IDL.Func(
      [StudentId, AssignmentTitle, IDL.Text],
      [SubmissionId],
      [],
    ),
  'generateFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], []),
  'getAllFeedbackForStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(GeneratedFeedback)],
      ['query'],
    ),
  'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubmissionsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeedbackSubmission)],
      ['query'],
    ),
  'getFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], ['query']),
  'getInstructor' : IDL.Func([InstructorId], [Instructor], ['query']),
  'getStudent' : IDL.Func([StudentId], [Student], ['query']),
  'getStudentStats' : IDL.Func(
      [StudentId],
      [IDL.Record({ 'totalSubmissions' : IDL.Nat, 'averageScore' : IDL.Int })],
      ['query'],
    ),
  'getSubmissionById' : IDL.Func(
      [SubmissionId],
      [FeedbackSubmission],
      ['query'],
    ),
  'getSubmissionNote' : IDL.Func([SubmissionId], [IDL.Text], ['query']),
  'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
  'registerInstructor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Pin],
      [InstructorId],
      [],
    ),
  'updateInstructor' : IDL.Func(
      [InstructorId, IDL.Text, IDL.Text, IDL.Text, Pin],
      [],
      [],
    ),
  'verifyInstructor' : IDL.Func([InstructorId, Pin], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StudentId = IDL.Text;
  const SubmissionId = IDL.Nat;
  const AssignmentTitle = IDL.Text;
  const Suggestion = IDL.Record({ 'text' : IDL.Text });
  const Time = IDL.Int;
  const GeneratedFeedback = IDL.Record({
    'suggestions' : IDL.Vec(Suggestion),
    'feedbackText' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'submissionId' : SubmissionId,
  });
  const Pin = IDL.Text;
  const InstructorId = IDL.Nat;
  const Instructor = IDL.Record({
    'pin' : Pin,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'instructorId' : InstructorId,
    'department' : IDL.Text,
  });
  const Student = IDL.Record({
    'studentId' : StudentId,
    'name' : IDL.Text,
    'course' : IDL.Text,
  });
  const FeedbackSubmission = IDL.Record({
    'studentId' : IDL.Text,
    'timestamp' : Time,
    'submissionText' : IDL.Text,
    'submissionId' : SubmissionId,
    'assignmentTitle' : AssignmentTitle,
  });
  const SystemStats = IDL.Record({
    'topStudent' : IDL.Opt(
      IDL.Record({ 'studentId' : StudentId, 'averageScore' : IDL.Int })
    ),
    'totalStudents' : IDL.Nat,
    'totalSubmissions' : IDL.Nat,
    'overallAverageScore' : IDL.Int,
  });
  
  return IDL.Service({
    'addStudent' : IDL.Func([StudentId, IDL.Text, IDL.Text], [], []),
    'addSubmissionNote' : IDL.Func([SubmissionId, IDL.Text], [], []),
    'createSubmission' : IDL.Func(
        [StudentId, AssignmentTitle, IDL.Text],
        [SubmissionId],
        [],
      ),
    'generateFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], []),
    'getAllFeedbackForStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(GeneratedFeedback)],
        ['query'],
      ),
    'getAllInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubmissionsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeedbackSubmission)],
        ['query'],
      ),
    'getFeedback' : IDL.Func([SubmissionId], [GeneratedFeedback], ['query']),
    'getInstructor' : IDL.Func([InstructorId], [Instructor], ['query']),
    'getStudent' : IDL.Func([StudentId], [Student], ['query']),
    'getStudentStats' : IDL.Func(
        [StudentId],
        [
          IDL.Record({
            'totalSubmissions' : IDL.Nat,
            'averageScore' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getSubmissionById' : IDL.Func(
        [SubmissionId],
        [FeedbackSubmission],
        ['query'],
      ),
    'getSubmissionNote' : IDL.Func([SubmissionId], [IDL.Text], ['query']),
    'getSystemStats' : IDL.Func([], [SystemStats], ['query']),
    'registerInstructor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Pin],
        [InstructorId],
        [],
      ),
    'updateInstructor' : IDL.Func(
        [InstructorId, IDL.Text, IDL.Text, IDL.Text, Pin],
        [],
        [],
      ),
    'verifyInstructor' : IDL.Func([InstructorId, Pin], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };