/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssignmentTitle = string;
export interface FeedbackSubmission {
  'studentId' : string,
  'timestamp' : Time,
  'submissionText' : string,
  'submissionId' : SubmissionId,
  'assignmentTitle' : AssignmentTitle,
}
export interface GeneratedFeedback {
  'suggestions' : Array<Suggestion>,
  'feedbackText' : string,
  'score' : bigint,
  'timestamp' : Time,
  'submissionId' : SubmissionId,
}
export interface Student {
  'studentId' : StudentId,
  'name' : string,
  'course' : string,
}
export type StudentId = string;
export type SubmissionId = bigint;
export interface Suggestion { 'text' : string }
export type Time = bigint;
export interface _SERVICE {
  'addStudent' : ActorMethod<[StudentId, string, string], undefined>,
  'createSubmission' : ActorMethod<
    [StudentId, AssignmentTitle, string],
    SubmissionId
  >,
  'generateFeedback' : ActorMethod<[SubmissionId], GeneratedFeedback>,
  'getAllFeedbackForStudent' : ActorMethod<
    [StudentId],
    Array<GeneratedFeedback>
  >,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllSubmissionsByStudent' : ActorMethod<
    [StudentId],
    Array<FeedbackSubmission>
  >,
  'getFeedback' : ActorMethod<[SubmissionId], GeneratedFeedback>,
  'getStudent' : ActorMethod<[StudentId], Student>,
  'getStudentStats' : ActorMethod<
    [StudentId],
    { 'totalSubmissions' : bigint, 'averageScore' : bigint }
  >,
  'getSubmissionById' : ActorMethod<[SubmissionId], FeedbackSubmission>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];